fix: tidy up Dockerfile and remove unnecessary items
NebraLtd/hm-pktfwd pull request #22
Opened 2021-07-31 23:12 UTC by shawaj

- Change to MIT license and update company name
- add inline comments
- remove unnecessary build steps
- remove wget from runner
- make files executable and remove chmod commands from dockerfile

2021-08-01 00:22 UTC, shawaj commented
cc @ marvinmarnold @vpetersson @robputt if you could take a look and see if this all makes sense 👍 

i am sure there is more that can be improved, but hopefully this is a useful initial stab

2021-08-01 07:37 UTC, vpetersson commented
@shawaj Don't leave commented code behind in the files. If we need to revert it later, we can pull the history from `git`.

2021-08-01 09:37 UTC, shawaj commented
@vpetersson where did you find the commented code? Think I removed the last of it in the latest commit?

2021-08-01 09:42 UTC, vpetersson commented
> @vpetersson where did you find the commented code? Think I removed the last of it in the latest commit?

My bad. Either i reviewed a previous version or i misread.

2021-08-01 09:42 UTC, vpetersson commented
@robputt / @marvinmarnold could either of you review this please?

2021-08-01 09:42 UTC, shawaj commented
@vpetersson have squashed the commits to make it easier :-)

2021-08-01 16:26 UTC, marvinmarnold requested changes
The security audit is broken. That's the only real blocker. Everything else is stylistic and consistency comments with other in-flight work.

2021-08-01 16:26 UTC, marvinmarnold commented on Dockerfile
> +FROM arm32v5/debian:buster-slim as builder
Is there a reason to use a different image than for hm-config which uses `balenalib/raspberry-pi-debian`?

2021-08-01 16:26 UTC, marvinmarnold commented on Dockerfile
> +            pip3 install --no-cache-dir sentry-sdk==1.1.0
We can use venv to install dependencies in [builder](https://github.com/NebraLtd/hm-config/pull/52/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R23) and copy everything over to [runner](https://github.com/NebraLtd/hm-config/pull/52/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R76). This works because venv is installed and the [PATH is hijacked](https://github.com/NebraLtd/hm-config/pull/52/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R77).

2021-08-01 16:26 UTC, marvinmarnold commented on Dockerfile
> +RUN wget -q "https://raw.githubusercontent.com/NebraLtd/helium-hardware-definitions/d84ee2af049b9c033c07788bea577a459aeb3aaa/variant_definitions.py"
My proposal is that we copy this dependency into source control. For now, this can be done manually. In the future, we can reference an actual release of helium-hardware-definitions. 

Eg: https://github.com/NebraLtd/hm-config/commit/b5e08e48e05d58adb9681e9b3e182d1cdcd771d8

2021-08-01 16:45 UTC, robputt commented on Dockerfile
> +RUN wget -q "https://raw.githubusercontent.com/NebraLtd/helium-hardware-definitions/d84ee2af049b9c033c07788bea577a459aeb3aaa/variant_definitions.py"
Use git submodule?

2021-08-01 16:48 UTC, robputt approved these changes
I concur with Marvin's comments. Going to approve rather than have a double block on the merge.

2021-08-01 19:22 UTC, shawaj commented on .github/workflows/security-audit.yml
> +        bandit -r config-python
Oops copied it from the other repo.

Is it better to just run the check on `files/` or on the whole repo?

2021-08-01 19:58 UTC, shawaj commented on Dockerfile
> +FROM arm32v5/debian:buster-slim as builder
No reason as far as I'm aware. 

Looks like balenalib/raspberry-pi-debian will run fine on armv6 so don't see an issue with that.

The only thing I can think is that maybe arm32v5/debian:buster-slim is a smaller image?

2021-08-03 02:56 UTC, shawaj commented on Dockerfile
> +RUN wget -q "https://raw.githubusercontent.com/NebraLtd/helium-hardware-definitions/d84ee2af049b9c033c07788bea577a459aeb3aaa/variant_definitions.py"
so do you want me to do anything here for now? or is this just a suggestion for future?

2021-08-03 03:00 UTC, shawaj commented on Dockerfile
> +FROM arm32v5/debian:buster-slim as builder
changed to balenalib/raspberry-pi-debian now :-)

2021-08-03 03:01 UTC, shawaj commented on .github/workflows/security-audit.yml
> +        bandit -r config-python
fixed - although security check is failing so need to resolve that next

2021-08-03 04:44 UTC, shawaj commented on Dockerfile
> +            pip3 install --no-cache-dir sentry-sdk==1.1.0
@marvinmarnold could you take a look at how I have done it in here: https://github.com/NebraLtd/hm-pktfwd/blob/acbf197b5f370d3a4cfce163434e386daa684646/Dockerfile#L14

Does that look correct?

2021-08-03 13:59 UTC, marvinmarnold commented on Dockerfile
> -            python3-rpi.gpio=0.6.5-1 \
TBH I'm unsure if we want to remove `python3-rpi.gpio`. Not clear to me if the relevant system dependencies are copied with venv. If we had more comprehensive testing, I'd recommend we remove it and see what happens. In reality it may be best to keep it and for now and readdress later.

2021-08-03 13:59 UTC, marvinmarnold commented on Dockerfile
> +            pip3 install --no-cache-dir sentry-sdk==1.1.0
Yup!

2021-08-03 14:39 UTC, marvinmarnold commented on Dockerfile
> +RUN wget -q "https://raw.githubusercontent.com/NebraLtd/helium-hardware-definitions/d84ee2af049b9c033c07788bea577a459aeb3aaa/variant_definitions.py"
I think submodules are easy to do wrong. I'd rather prioritize doing it the right way -- publishing an official release of `helium-hardware-definitions`.

Until then, I still think we should download `variant_definitions.py` and [bundle it with the source control](https://github.com/NebraLtd/hm-config/pull/54/commits/5b20243dff2abde83de1bd952f5457f20882323c#diff-22d482645b486c096cb7f7f3cbf024cb3c1177b4a248582e9d4a941e5c94ec36). This will be more annoying to maintain because we'll have to manually update it anytime things change. But at least this way the source code will compile locally.

2021-08-03 16:11 UTC, shawaj commented on Dockerfile
> -            python3-rpi.gpio=0.6.5-1 \
@marvinmarnold i tested it on the `light-hotspot-software` and it seems to work fine in regards to everything it needs to do with GPIO...however, not super extensive testing...but it was able to properly configure and start the lora concentrator.

However, can move it back if you think it is best to do so?

2021-08-03 16:14 UTC, shawaj commented
@marvinmarnold @robputt the only thing I am not sure of now is how to fix the python security audit issues.

Have taken them down from "high" severity to "low" however still throwing up errors and out of my depth now.

I guess the answer is maybe to directly implement them in python rather than using subprocess, but not sure if that is possible?

2021-08-03 16:23 UTC, shawaj commented on Dockerfile
> +RUN wget -q "https://raw.githubusercontent.com/NebraLtd/helium-hardware-definitions/d84ee2af049b9c033c07788bea577a459aeb3aaa/variant_definitions.py"
@marvinmarnold ok have done that now. 

added in a `COPY lib lib` command to the dockerfile for the variant_definitions.py but not sure if this is actually required?

2021-08-03 21:13 UTC, marvinmarnold commented on Dockerfile
> +RUN wget -q "https://raw.githubusercontent.com/NebraLtd/helium-hardware-definitions/d84ee2af049b9c033c07788bea577a459aeb3aaa/variant_definitions.py"
Yea, good call out. Copying lib is necessary until we can turn it into a a dependency installed with pip.

2021-08-03 21:39 UTC, marvinmarnold commented on Dockerfile
> -            python3-rpi.gpio=0.6.5-1 \
Did some more digging but I haven't been able to convince myself its not necessary. Lets leave `python3-rpi.gpio` in runner for now. There's not a huge cost in doing so. Sorry for recommending you switch back and forth!

2021-08-03 22:28 UTC, marvinmarnold commented
> EDIT: looks like it is not possible to pass this test due to an [error in its implementation](https://github.com/PyCQA/bandit/issues/333) so perhaps we just need to add `# nosec` to these lines?

Agreed that `#nosec` is the best fix until this is fixed upstream.

2021-08-04 01:26 UTC, shawaj commented on Dockerfile
> -            python3-rpi.gpio=0.6.5-1 \
ok have moved back into the runner :-)

2021-08-04 01:42 UTC, shawaj commented
> Agreed that `#nosec` is the best fix until this is fixed upstream.

@marvinmarnold ok added that now too.

Have re-requested review as think that is all sorted now and all checks / builds seem to be passing

2021-08-04 17:26 UTC, marvinmarnold approved these changes
Awesome!

2021-08-04 17:53 UTC, merged