Refactor build process
NebraLtd/hm-pktfwd pull request #59
Opened 2021-10-20 15:45 UTC by marvinmarnold

**Why**
The hm-pktfwd build process is confusing. We have decided to split up the build process by repo instead of having a mono-Dockerfile in hm-pktfwd.

**How**
nebraltd/lora_gateway, nebraltd/packet_forwarder, and nebraltd/sx1302_hal are now built independently and the necessary assets are pulled into the hm-pktfwd build process.

**References**

- Closes: https://github.com/NebraLtd/hm-pktfwd/issues/45
- Closes: https://github.com/NebraLtd/hm-pktfwd/issues/44
- Closes: https://github.com/NebraLtd/hm-pktfwd/issues/60
- Depends on: https://github.com/NebraLtd/lora_gateway/pull/2
- Depends on: https://github.com/NebraLtd/packet_forwarder/pull/2
- Depends on: https://github.com/NebraLtd/sx1302_hal/pull/1
- Depends on: https://github.com/NebraLtd/hm-pyhelper/pull/31
- Closed all-in-one proposal: https://github.com/NebraLtd/hm-pktfwd/pull/58
- Incorrectly opened here originally: https://github.com/Lora-net/lora_gateway/pull/172

2021-10-20 20:38 UTC, shawaj commented on pktfwd/utils.py
> +    Original code: https://github.com/NebraLtd/hm-pktfwd/blob/5a0178341e69ecbf6b1dbc8463f6bd1231e9e657/files/configurePktFwd.py#L77  # noqa: E501
@marvinmarnold no idea to be honest. 

It was introduced in the original commit at 10 seconds...
https://github.com/NebraLtd/hm-pktfwd/commit/c56a5e5a9560f080a07d3284c2a09a1bbdef31d0#diff-067eec9a2dc1fbb37d3e0f4c8537fe6ff095e0b9a37a6e5e95ff30bb4bdcd6e8

And then reduced to 5 seconds here...
https://github.com/NebraLtd/hm-pktfwd/commit/fa4f3e256929338f473be322e821c80a4991552f#diff-067eec9a2dc1fbb37d3e0f4c8537fe6ff095e0b9a37a6e5e95ff30bb4bdcd6e8

I can't see any point in it really to be honest. We should test without it IMO and see if it affects anything

2021-10-21 01:22 UTC, shawaj requested changes

2021-10-21 01:37 UTC, shawaj commented on pktfwd/utils.py
> +    subprocess.run([reset_lgw_filepath, "stop", reset_lgw_pin_str])
See here for sx1302 https://github.com/NebraLtd/sx1302_hal/pull/1#discussion_r733253225

For sx1301 it looks like we aren't actually currently using the reset script. See...
https://github.com/NebraLtd/packet_forwarder/blob/c43e727fc578a0685a428c6e3a775cdf7e80f860/lora_pkt_fwd/src/lora_pkt_fwd.c#L1193-L1200

And

https://github.com/NebraLtd/lora_gateway/blob/971c52e3e0f953102c0b057c9fff9b1df8a84d66/libloragw/src/loragw_hal.c#L696-L1089

However, in the original repo it says we should reset so it seems like this is best practice:
https://github.com/NebraLtd/lora_gateway#31-reset_lgwsh

2021-10-21 01:39 UTC, shawaj commented
Generally looks really good apart from the questions / comments above 👍🥳

2021-10-21 01:45 UTC, shawaj commented on Dockerfile
> +# Copy sx1301 reset_lgw.sh
Probably can just use the same reset script for sx1301 and sx1302 unless there is a particular reason not to?

2021-10-21 17:09 UTC, marvinmarnold commented on pktfwd/utils.py
> +    subprocess.run([reset_lgw_filepath, "stop", reset_lgw_pin_str])
Very helpful links. I did intentionally add the reset because of the comment in in the lora_gateway readme. I think we should keep it for that reason for sx1301. But resetting before sx1302 does seem redundant because it is already called, like you point out. So keep reset for sx1301 and remove for sx1302.

2021-10-21 21:49 UTC, marvinmarnold commented on pktfwd/utils.py
> +def write_diagnostics(diagnostics_filepath, is_running):
I'm not sure what this file is trying to communicate. That the lora packet_forwarder is running successfully? That python hm-pktfwd app is running? The former seems useful but we wouldn't want to block diag from starting up just because the packet forwarder won't start, would we? Also, that's not what the file currently represents.

If we are trying to communicate the latter, that the python app is running, that doesn't seem like very useful information because the python app can run even if the concentrator fails to start. I'd also argue that typically the python app will always start as long as the container starts. In that case, we might as well use a normal depends_on without a healthcheck and remove the file logic all together. 

Finally, what we [decide for max_retries](https://github.com/NebraLtd/hm-pktfwd/pull/59#discussion_r733232171), will impact the meaning of this file.

2021-10-21 23:44 UTC, shawaj commented on pktfwd/utils.py
> +def write_diagnostics(diagnostics_filepath, is_running):
i was sleepy and misunderstood what this file was for and that it wasn't a new addition. 

as mentioned above it already is being used in hm-diag...

https://github.com/NebraLtd/hm-diag/blob/9ba78481584cacf8bb5aede8faae136da80085e1/hw_diag/utilities/hardware.py#L76-L94

basically this is used in hm-diag to show if there is an error with the packet_forwarder / lora concentrator starting up.

essentially this is a duplicate of [my comment above](https://github.com/NebraLtd/hm-pktfwd/pull/59#discussion_r733232171)

we just need a way that the retrying of starting the Lora concentrator is not coupled to the reading of the status of the lora module starting up - if that makes sense

2021-10-23 00:01 UTC, marvinmarnold commented on pktfwd/utils.py
> +        write_diagnostics(diagnostics_filepath, lora_pkt_fwd_proc_is_running)
What is the desired behavior at this point? As-is this would lead to the program exiting and the Docker container restarting. It would be faster to throw an exception here which would cause `retry_start_concentrator` to run forever.

The drawback is that if the concentrator exited for a reason that requires a container restart, it will get stuck. Any opinions on which strategy is better?

2021-10-23 00:22 UTC, marvinmarnold commented on pktfwd/utils.py
> +        sleep(LORA_PKT_FWD_RETRY_SLEEP_SECONDS)
This leads to True being rewritten to the file constantly when running.

2021-10-23 00:57 UTC, shawaj commented on pktfwd/utils.py
> +def write_diagnostics(diagnostics_filepath, is_running):
Yeah that looks good. 

Yeah the retry and polling interval probably don't need to be the same.

And yeah usually if the concentrator starts up it's less likely that it then fails (although of course possible). It's more likely to be the starting up that fails. But both need to be handled.

The only thing I'm concerned about is slowing down the time to return True to initFile.txt which is used in the Hotspot-Production-Tool so maybe the retry and polling interval could be tailored accordingly

2021-10-26 16:55 UTC, merged